{% set name = "ipsurv" %}
{% set version = "1.3.1" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipsurv-{{ version }}.tar.gz
  sha256: 3c3c19c09fa3173ed514dc7281088093b57b4e8609136be86e21065c5f69c22a

build:
  number: 0
  noarch: python
  entry_points:
    - ipsurv = ipsurv.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - dnspython
    - python >={{ python_min }}

test:
  imports:
    - ipsurv
  commands:
    - pip check
    - ipsurv --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://deer-hunt.github.io/ipsurv/
  license: MIT
  license_file: LICENSE.md
  summary: '"IpSurv" is the tools for IP address and network investigation. There are multiple commands. Investigating IP information, server response, and packet capture tool like "tcpdump".'
  description: |
    "ipsurv" can investigate IP address information and the response status of external server.
    "ipscap" is a packet capture tool similar to "tcpdump". "ipscap" has various filtering options, displays IP-header and TCP-header, UDP-header, and dumping files functions.
    "ipsend" is a network transmission tool that supports TCP, SSL, UDP, and Raw sockets, as well as interactive transmission.
  dev_url: https://github.com/deer-hunt/ipsurv
  doc_url: https://deer-hunt.github.io/ipsurv/

extra:
  recipe-maintainers:
    - deer-hunt
